#!/usr/bin/env python3
# -*- mode: python; -*-

import argparse
import codecs

def read_file(filename, encoding = "utf8"):
    return codecs.open(filename, "r", encoding).read()

def process(filename):
    freq = {}

    content = read_file(filename)
    lines = content.split("\n")
    for line in lines:
        line = line.strip().replace("\t", " ")
        if " lds " in line or " sts " in line:
            _, comment = line.split(";", 1)
            vname = comment.split("<", 1)[1].split(">", 1)[0]
            if vname in freq:
                freq[vname] += 1
            else:
                freq[vname] = 1

    items = []
    for k in freq:
        items.append((k, freq[k]))

    ALIGN=60

    items.sort(key = lambda x: -x[1])
    print("VARIABLE".ljust(ALIGN), "LOADS and STORES")
    for item in items[:20]:
        print(item[0].ljust(ALIGN), item[1])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Macro preprocessor by Akshaal')

    parser.add_argument('file', type = str, help = 'files to preprocess')

    cmd_args = parser.parse_args()

    process(cmd_args.file)
